---
title: "Editores de texto | LMWeb"
author: "Víctor Peinado"
date: "2 de marzo de 2016"
output: rmarkdown::tufte_handout
---

# Editores de texto profesionales

En clase (y en casa) vamos a utilizar dos **editores de texto** más potentes que el bloc de notas que ya conocemos: se trata de Notepad++[^notepad] y atom[^atom].

Las características principales de estos editores profesionales frente a editores de texto sencillos son:

- Numeración de líneas.
- Resaltado de sintaxis.
- Multidocumento.
- Macros.
- Autocompletado.
- Modo de búsqueda avanzado.
- Altamente configurable.


# Pintando en texto plano

Si necesidad de hacer arte ASCII[^asciiart], vamos a tratar de replicar en formato texto los cinco documentos siguientes:

- Este documento.
- Una carta más o menos formal.[^carta]
- Una entrada del DRAE.[^drae]
- Una tabla con resultados de una competición.[^tabla]
- El típico texto de lingüística.[^yule]


[^notepad]: Notepad++: http://notepad-plus-plus.org

[^atom]: atom: http://www.atom.io

[^asciiart]: ASCII Art: http://en.wikipedia.org/wiki/ASCII_art

[^carta]: https://abelsuing.files.wordpress.com/2010/02/carta-agradecimiento-abel-swing.jpg

[^drae]: http://lema.rae.es/drae/?val=torre

[^tabla]: http://resultados.as.com/resultados/baloncesto/acb/2014_2015/clasificacion

[^yule]: http://vitojph.github.io/ling/lmweb/yule.pdf